[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mysolanaapp = "G7B1jSx3HiXhDaqQ3LYgx1WA16PhFvpV8bxXxjnD6j6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shada/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
